### ISSUE TITLE
ci/circleci: upload-linux — Your tests failed

### ISSUE THREAD

**Issue by huidongchen** [bioconda/bioconda-recipes#13010]
Hi,

My recipe was successfully built #13008 but later I got the error 

"Some checks were not successful
1 failing and 1 successful checks
ci/circleci: upload-linux — Your tests failed"

Do I need to rebuild it? I'm a bit confused why this error still happens since it already passed the test. 

Thanks!

**Comment by dpryan79** [comment]
Looks like this is now resolved. If not, please reopen.

**Comment by huidongchen** [comment]
Hi,

Unfortunately the issue is not really solved. Sorry if I didn't make it clear. Let me try to explain it better. 

'stream' recipe building DID pass all the tests on CircleCI. 

But **after** the commit is merged into master branch, there is a **second-round CircleCI testing** showing **'upload-linux'** and **'upload-macos'** in the **'commit'** page. 'stream' recipe failed there. ('stream' can be still installed via bioconda though) 

I'm attaching a screenshot. Hope this will be helpful.  Thanks!

<img width="830" alt="screen shot 2019-01-22 at 12 58 01" src="https://user-images.githubusercontent.com/20446151/51556057-15dfa380-1e47-11e9-9a18-cce0b848c368.png">

**Comment by dpryan79** [comment]
Everything was a success. After it uploads it cleans everything up, which can take a few minutes. If that cleanup period takes more than 10 minutes circleci will fail. It was uploaded successfully, though, so this can be ignored.
