### ISSUE TITLE
Antismash 4 fails to run

### ISSUE THREAD

**Issue by ruy-jauregui** [bioconda/bioconda-recipes#15561]
Hello! I tried to run the last two versions of the Antismash 4 package and I get the same error:
(/home/jaureguir/conda-envs/antismash4) jaureguir@grabfopp02:~/genomes/assemblies$ antismash --taxon fungi genome.contigs.fasta
ERROR   21/05 11:05:49   Failed to run GlimmerHMM: 'ERROR 1:  Unable to open file /home/jaureguir/conda-envs/antismash4/lib/python2.7/site-packages/antismash/generic_modules/genefinding/train_crypto/config.file\n'

**Comment by tseemann** [comment]
@kblin is this the correct python?

**Comment by kblin** [comment]
This is a packaging error with the bioconda package of antiSMASH 4.1.0, where not all files required for GlimmerHMM gene finding are packaged. This is fixed in 4.2.0, but for some reason the package never made it to bioconda.

As a quick fix, you can grab the files from https://bitbucket.org/antismash/antismash/src/master/antismash/generic_modules/genefinding/train_crypto/ and put them into `/home/jaureguir/conda-envs/antismash4/lib/python2.7/site-packages/antismash/generic_modules/genefinding/train_crypto/`

Alternatively, and maybe the better solution, you can run a dedicated fungal gene finding tool on your fungal genome, and then run antiSMASH with either a Genbank file or with a GFF3 file (+ FASTA for the sequence in that case) containing the gene/CDS annotations.

That said, the current version of antiSMASH is 5.0.0, and we don't really have the resources to support older versions.

**Comment by bgruening** [comment]
@kblin 4.2 is here: https://anaconda.org/bioconda/antismash/files ... 5 is missing afaik. Is 4.2 still broken?

**Comment by kblin** [comment]
4.2 should be fine, we get a lot of people still installing 4.1, though..

**Comment by druvus** [comment]
Issue fixed in version 4.2 so closing.
