### ISSUE TITLE
Cannot build recipes

### ISSUE THREAD

**Issue by christiam** [bioconda/bioconda-recipes#15672]
Hi,
      I'm trying to build the bioconda recipes repo (following these [instructions](https://bioconda.github.io/contribute-a-recipe.html)), but neither the circleci approach nor the bootstrap.py approach work for me. In the former I encountered the error `git: command not found` (see [here](https://gist.github.com/christiam/0442ea61cb57b8b9e1523d33ac40f3bb#file-bioconda-build-circleci-log-L56)); in the latter the error is not as clear to me (see output [here](https://gist.github.com/christiam/a5a4ff213cbd7947b49485a5edc44073#file-bioconda-build-bootstrap-log-L806)). Could you please shed some light into this? Am I missing something?
Many thanks, regards,

Christiam

**Comment by npavlovikj** [comment]
I would suggest you to always use `bioconda-utils` - it does the more stringent mulled-test that are performed on the build system anyways. I have never been able to have `circleci build` running, and I have heard of other people having similar issues as well. 

Regarding the `bioconda-utils` errror you have, that was fixed last week (see https://github.com/bioconda/bioconda-utils/issues/553), so please make sure your "bioconda" repo is up to date and then try `boostrap` again.

**Comment by christiam** [comment]
@npavlovikj ,
        Thanks. I updated my fork, re-ran `bootstrap.py`, and now `bioconda-utils -h` now doesn't fail. However, after doing some changes to the recipes, I ran `bioconda-utils build recipes config.yml --docker --mulled-test --git-range master` and I got the message below:

`BIOCONDA INFO No recipe modified according to git, exiting.`

Running the lint step produced the error below:
```
$ bioconda-utils lint recipes config.yml --git-range master
06:29:59 BIOCONDA INFO Considering total of 6749 recipes.
06:29:59 BIOCONDA INFO Constraining to 0 git modified recipes.
0it [00:00, ?it/s]
Errors were found
$
```

Also, I ran `bioconda-utils update recipes/ config.yml --packages <my-package-name>` and I get the error: `bioconda-utils: error: invalid choice: 'update' (choose from 'build', 'dag', 'dependent', 'lint', 'duplicates', 'update-pinning', 'bioconductor-skeleton', 'clean-cran-skeleton', 'autobump', 'bot')`.

Do you have any suggestions on how to address these?
Thanks, regards,

Christiam

**Comment by npavlovikj** [comment]
Hi @christiam ,

I am glad to hear that `bootstrap` works fine for you now.

Regarding updating a recipe - the documentation hasn't been updated yet, but you should use `autobump` instead of `update`.

For the `BIOCONDA INFO No recipe modified according to git, exiting.` message - did you increase the build number in `meta.yaml`? That message usually appears when the build number is not increased, and thus no new recipe to be built is detected. Just in case, these are the steps I usually use:
```
git checkout -b branch
# modify file(s), increase build number etc.
git add file(s)
source ~/.config/bioconda/activate
bioconda-utils build recipes config.yml --docker --git-range master --mulled-test
source deactivate
```
where "branch" is the name of the branch you are working on, and "file(s)" are the recipe files you are modifying.

I hope this helps.

**Comment by npavlovikj** [comment]
@christiam , I just did `bootstrap` in a clean env, and I needed to replace:
`bioconda-utils build recipes config.yml --docker --git-range master --mulled-test`
with
`bioconda-utils build recipes config.yml --docker --mulled-test --packages RECIPE`
in the commands above to build the recipe RECIPE.

Can you maybe try that instead if you are still encountering issues?

@epruesse , sorry for bothering you, but do you know why `--git-range master` from a branch on a bioconda fork is reporting `No recipe modified according to git, exiting.` now (the exact steps are in my previous comment)? I believe this change has happened in the last 3-4 days, so I just want to verify what the correct command should be.

**Comment by christiam** [comment]
@npavlovikj ,
       Thanks. I tried your latest suggestion but the build still failed, though I'm not sure whether this is because of the changes I made or something else (log file: [build-blast-post-commit-single-recipe.log.gz](https://github.com/bioconda/bioconda-recipes/files/3247291/build-blast-post-commit-single-recipe.log.gz)).

**Comment by npavlovikj** [comment]
@christiam , looks like `bioconda-utils` is working fine for you, and the errors you are gettitng now are recipe specific. 

Is there a reason why you are building blast 2.9.0? That recipe is already available in Bioconda, https://github.com/bioconda/bioconda-recipes/blob/0a57bb0a86a96da67603332ed0c08d4c20af17c0/recipes/blast/meta.yaml.

**Comment by christiam** [comment]
@npavlovikj ,
          I'd like to remove outdated dependencies and fix a missing one.

**Comment by npavlovikj** [comment]
I see... I believe you are modifying the current recipe then? I think Blast is not easy to build from source at all, but you can start with the current recipe. Also, if you open a PR here with your changes, you can ask someone from the core team that did the previous Blast recipe to help you and verify the changes.

I think your build system is properly set now, so have fun building the recipes next :)

**Comment by christiam** [comment]
@npavlovikj ,
        I have a successful build, but I'm unable to run `bioconda-utils autobump recipes/ config.yml --packages blast`. It fails with the following error (full output: [autobump.log.gz](https://github.com/bioconda/bioconda-recipes/files/3254037/autobump.log.gz):

```
18:38:28 BIOCONDA ERROR Dropping into debugger
Traceback (most recent call last):
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 70, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-17>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 89, in wrapper
    func(*args, **kwargs)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 799, in autobump
    config_dict, cache_fn=cache and cache + "_dag.pkl")
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/autobump.py", line 132, in __init__
    self.dag = self.load_graph()
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/autobump.py", line 166, in load_graph
    recipe for recipe in recipes_load_parallel_iter(self.recipe_base, "*")
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/graph.py", line 112, in build_from_recipes
    for recipe in recipe_list
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/networkx/classes/digraph.py", line 635, in add_edges_from
    for e in ebunch:
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/graph.py", line 113, in <genexpr>
    for dep in recipe.get_deps()
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/recipe.py", line 631, in get_deps
    return list(self.get_deps_dict(sections, output).keys())
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/recipe.py", line 648, in get_deps_dict
    dep = spec.split()[0]
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/tmp/miniconda/miniconda/bin/bioconda-utils", line 10, in <module>
    sys.exit(main())
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 905, in main
    bioconductor_skeleton, clean_cran_skeleton, autobump, bot
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "<boltons.funcutils.FunctionBuilder-20>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 126, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-19>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 58, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-18>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 70, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-17>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 89, in wrapper
    func(*args, **kwargs)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 799, in autobump
    config_dict, cache_fn=cache and cache + "_dag.pkl")
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/autobump.py", line 132, in __init__
    self.dag = self.load_graph()
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/autobump.py", line 166, in load_graph
    recipe for recipe in recipes_load_parallel_iter(self.recipe_base, "*")
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/graph.py", line 112, in build_from_recipes
    for recipe in recipe_list
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/networkx/classes/digraph.py", line 635, in add_edges_from
    for e in ebunch:
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/graph.py", line 113, in <genexpr>
    for dep in recipe.get_deps()
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/recipe.py", line 631, in get_deps
    return list(self.get_deps_dict(sections, output).keys())
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/recipe.py", line 648, in get_deps_dict
    dep = spec.split()[0]
AttributeError: 'NoneType' object has no attribute 'split'

```

Do you have any suggestions on how to address this?
Many thanks again, regards,

Christiam

**Comment by epruesse** [comment]
@christiam The above error was fixed in v0.16.0

**Comment by christiam** [comment]
@epruesse ,
       How do I get the fix? I sync'd my fork with the upstream repo and I still get errors:

```
$ bioconda-utils autobump recipes/ config.yml --packages blast
21:05:04 BIOCONDA INFO Hosters loaded: ['FTPHoster', 'GithubRelease', 'GithubTag', 'GithubReleaseAttachment', 'GithubRepoStore', 'Bioconductor', 'CargoPort', 'SourceForge', 'PyPi', 'Bioarchive', 'CPAN', 'CRAN', 'BitBucketTag', 'BitBucketDownload', 'GitlabTag']
21:05:04 BIOCONDA WARNING Selected 3 packages
21:05:04 BIOCONDA INFO Building Recipe DAG
21:05:05 BIOCONDA INFO pubchempy has duplicate key                                                                                                                                                                                                                                                                          
21:05:05 BIOCONDA INFO scoary has duplicate key                                                                                                                                                                                                                                                                             
21:05:05 BIOCONDA INFO platypus-conquistador has duplicate key                                                                                                                                                                                                                                                              
21:05:05 BIOCONDA INFO sierrapy has duplicate key                                                                                                                                                                                                                                                                           
21:05:06 BIOCONDA INFO r-smartsva has duplicate key                                                                                                                                                                                                                                                                         
21:05:06 BIOCONDA INFO bioconductor-breastcancerupp has duplicate key                                                                                                                                                                                                                                                       
21:05:06 BIOCONDA INFO segemehl/0.2.0 has duplicate key                                                                                                                                                                                                                                                                     
21:05:06 BIOCONDA INFO segemehl has duplicate key                                                                                                                                                                                                                                                                           
21:05:06 BIOCONDA INFO segemehl/0.3.1 has duplicate key                                                                                                                                                                                                                                                                     
21:05:07 BIOCONDA INFO sourcetracker has duplicate key                                                                                                                                                                                                                                                                      
21:05:07 BIOCONDA INFO cufflinks has duplicate key                                                                                                                                                                                                                                                                          
21:05:08 BIOCONDA INFO homer has duplicate key                                                                                                                                                                                                                                                                              
21:05:08 BIOCONDA INFO msms has duplicate key                                                                                                                                                                                                                                                                               
21:05:08 BIOCONDA INFO nim-falcon has duplicate key                                                                                                                                                                                                                                                                         
21:05:09 BIOCONDA INFO r-isva has duplicate key                                                                                                                                                                                                                                                                             
21:05:09 BIOCONDA INFO stellar has duplicate key                                                                                                                                                                                                                                                                            
21:05:10 BIOCONDA INFO igblast/1.4.0 has duplicate key                                                                                                                                                                                                                                                                      
21:05:11 BIOCONDA INFO spades/3.11.1 has duplicate key                                                                                                                                                                                                                                                                      
21:05:11 BIOCONDA INFO amptk has duplicate key                                                                                                                                                                                                                                                                              
21:05:12 BIOCONDA INFO svtools has duplicate key                                                                                                                                                                                                                                                                            
21:05:12 BIOCONDA INFO s3gof3r has duplicate key                                                                                                                                                                                                                                                                            
21:05:13 BIOCONDA INFO fcsparser has duplicate key                                                                                                                                                                                                                                                                          
Loading Recipes...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6753/6753 [00:09<00:00, 713.09it/s]
21:05:14 BIOCONDA INFO Building Recipe DAG: done (2299 nodes, 8457 edges)
21:05:14 BIOCONDA ERROR Dropping into debugger
Traceback (most recent call last):
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 69, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-17>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 88, in wrapper
    func(*args, **kwargs)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 800, in autobump
    config_dict, cache_fn=cache and cache + "_dag.pkl")
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/autobump.py", line 133, in __init__
    self.dag = graph.filter_recipe_dag(self.dag, packages, exclude)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/graph.py", line 127, in filter_recipe_dag
    and not any(fnmatch(recipe.reldir, p) for p in exclude)):
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/tmp/miniconda/miniconda/bin/bioconda-utils", line 10, in <module>
    sys.exit(main())
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 906, in main
    bioconductor_skeleton, clean_cran_skeleton, autobump, bot
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "<boltons.funcutils.FunctionBuilder-20>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 125, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-19>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 57, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-18>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 69, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-17>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 88, in wrapper
    func(*args, **kwargs)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 800, in autobump
    config_dict, cache_fn=cache and cache + "_dag.pkl")
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/autobump.py", line 133, in __init__
    self.dag = graph.filter_recipe_dag(self.dag, packages, exclude)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/graph.py", line 127, in filter_recipe_dag
    and not any(fnmatch(recipe.reldir, p) for p in exclude)):
TypeError: 'NoneType' object is not iterable
```

**Comment by epruesse** [comment]
Which version do you have there? Try syncing with upstream / bioconda_bot.

**Comment by christiam** [comment]
@epruesse , 
      This is the latest commit I have as a resulting of syncing my fork with upstream/master. I do not see upstream/bioconda_bot in https://github.com/bioconda/bioconda-recipes.

`1b3b32845 Wed Jun 5 18:48:43 2019 | updated to 2.9.11 (#15735) (upstream/master, origin/master, origin/HEAD, master) [Francesco Beghini]`


> The above error was fixed in v0.16.0

I also do not see any such release/tag here: https://github.com/bioconda/bioconda-recipes/releases . 

Please advise, thanks again, regards,

Christiam

**Comment by epruesse** [comment]
Ah. The problem you encountered is not with the repository of recipes, but with the tool `bioconda-utils`. A couple of corner cases that weren't tested.

**Comment by christiam** [comment]
@epruesse  - thanks for the feedback.

@npavlovikj  - would you have any suggestions on how to workaround the issues in `bioconda-utils autobump`? Is this a pre-requisite to doing a PR?

**Comment by epruesse** [comment]
@christiam - you can do `@biocondabot autobump <nameofrecipe>` from gitter or here to get it to run autobump. That should work. Which recipe are you looking at?

Using autobump is not a requirement. You can always do a PR by hand.

It should be days only until autobump is running on a schedule on everything but bioconductor anyway.

**Comment by epruesse** [comment]
Also - if you are looking at BLAST - that's up to date, although autobump doesn't currently recognize it as it's hosted on an FTP with an unusual directory structure.

**Comment by christiam** [comment]
@epruesse - thanks. I'm updating the blast recipe. I'll submit the PR for review.

**Comment by epruesse** [comment]
The file is called 

```
https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.9.0/ncbi-blast-2.9.0+-src.tar.gz'
```

If it was

```
https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.9.0/ncbi-blast+-2.9.0-src.tar.gz'
```

it would be recognizable. But the `+` shifting from package name to version number is something too specific to catch. It'll need special config to check for that update.

**Comment by christiam** [comment]
@epruesse - thanks for the info, that sounds like a separate issue that should be addressed outside the context of this discussion.

Many thanks to you and @npavlovikj for all your help! 😃
