### ISSUE TITLE
Freebayes parallel and vcflib issues

### ISSUE THREAD

**Issue by jrderuiter** [bioconda/bioconda-recipes#2148]
Freebayes parallel is currently not working because the required vcflib scripts (such as vcffirstheader) are not copied over when freebayes is installed. This can be solved in two possible ways:
- We can build freebayes' vcflib submodule as part of the freebayes build and copy over the required scripts to the bin directory.
- Or we can make the freebayes package depend on the vcflib package and use the scripts from that package.

In both cases we would need to patch the freebayes-parallel script to look for the vcf scripts in PATH. 

The second option has my preference, as this separates the build scripts/requirements of freebayes and vcflib into the two distinct packages. This option does however require updating the vcflib package to a newer revision than is currently tagged as release candidate on github, as the release candidate does not include the required scripts. What would be the appropriate way to tag this newer version? In my own anaconda account I tagged the version as '1.0.0_rc1_head', although I am not sure if this is the ideal name for the newer build

**Comment by yesimon** [comment]
I actually wouldn't recommend making it depend on the vcflib package precisely because freebayes is vendoring it and is only promising for it to work with the specific vendored version. Looking at it briefly it seems like all references to vcflib scripts are relative instead of looking on the `$PATH` so checking out the submodule should work fine.

**Comment by bgruening** [comment]
@jrderuiter can you work on option 1?

**Comment by jrderuiter** [comment]
I'll try to have a go in the coming week or two!

**Comment by jrderuiter** [comment]
See 2588.

**Comment by jrderuiter** [comment]
See pull request #2588.

**Comment by tiagoantao** [comment]
Is there any update on this? Currently this is still not working, I think

**Comment by nsoranzo** [comment]
Fixed in https://github.com/bioconda/bioconda-recipes/pull/4422.

**Comment by Slugger70** [comment]
This is still not working.. Currently, freebayes-parallel.sh goes looking for the vcflib scripts in a specific location (../vcflib/bin/xxx).. The last part of the build.sh file copies them to $PREFIX/bin and so freebayes-parallel can't find them.

A solution would be to change the path in freebayes-parallel or to actually put them in the path specified in the script.. I guess the prefered solution would be to change the freebayes-parallel shell script so that the correct path is used..
