### ISSUE TITLE
kallisto 0.50.0 fails with "Illegal instruction"

### ISSUE THREAD

**Issue by ning-y** [bioconda/bioconda-recipes#42633]
Version 0.50.0 of kallisto on bioconda, using hdf5 version 1.12.2, fails with "Illegal instruction" when trying to index a FASTA file. The CLI interface works fine, though.

```
$ kallisto index --index Mus_musculus.GRCm39.cdna.all.idx inter/050-ref/Mus_musculus.GRCm39.cdna.all.fa.gz

Illegal instruction
$ kallisto version
kallisto, version 0.50.0                         
```

Downgrading to kallisto 0.48.0 with hdf5 1.12.1 fixes this.

```
  Package     Version  Build               Channel           Size 
───────────────────────────────────────────────────────────────────
Downgrade:
───────────────────────────────────────────────────────────────────
- hdf5       1.12.2  nompi_h4df4325_101  conda-forge     Cached
+ hdf5       1.12.1  nompi_h4df4325_104  conda-forge        4MB
- kallisto   0.50.0  hc877fd6_0          bioconda        Cached
+ kallisto   0.48.0  h15996b6_2          bioconda         589kB
Summary:
Downgrade: 2 packages
Total download: 4MB
───────────────────────────────────────────────────────────────────
```

**Comment by mjsteinbaugh** [comment]
I'm seeing a core dump error on Linux with kallisto 0.50.0 as well when attempting to index a genome. Building from source works as expected. Happy to help try to debug this.

**Comment by akkornel** [comment]
Hello!  Our site got the same issue.  `kallisto=0.50.0`, package file https://conda.anaconda.org/bioconda/linux-64/kallisto-0.50.0-hc877fd6_0.tar.bz2, from channel https://conda.anaconda.org/bioconda/linux-64.  I have figured out what the problem is, and why it's happening, but I don't know enough about cmake to figure out how it can be fixed.  But a fix will be needed, either by the maintainer of the package in Bioconda, or by the Kallisto folks.

The problem is, Kallisto vendors [bifrost](https://github.com/pmelsted/bifrost), and bifrost will use all available CPU features for the hardware it's built in, including AVX-512.  AVX-512 is the problem here, because many CPUs don't support it.  If you are getting an "Illegal Instruction" too, run `lscpu` and check your CPU model: You probably don't have AVX-512, or those specific features, either.

It is possible to build bifrost without using AVX-512, but I think that needs to be controlled through Kallisto (since bifrost is being vendored in Kallisto).  One workaround for the Bioconda maintainers is to build the package on a machine with an older CPU model, particularly one that does not have AVX-512.

The Kallisto folks have an issue for this too.  See pachterlab/kallisto#399.

The rest of this post explains how I figured out the problem.

Our cluster has a mix of AMD and Intel CPUs.  In this specific case, the user was running Kallisto on a system with two AMD EPYC 7402 24-Core Processors.  They're from the AMD EPYC 7002 "Rome" series.

<details><summary>lscpu output</summary>

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    1
Core(s) per socket:    24
Socket(s):             2
NUMA node(s):          2
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 49
Model name:            AMD EPYC 7402 24-Core Processor
Stepping:              0
CPU MHz:               1500.000
CPU max MHz:           2800.0000
CPU min MHz:           1500.0000
BogoMIPS:              5599.91
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
L3 cache:              16384K
NUMA node0 CPU(s):     0-23
NUMA node1 CPU(s):     24-47
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 hw_pstate sme ssbd rsb_ctxsw ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip overflow_recov succor smca
```

</details>

For the user whose Kallisto run failed, I managed to get a core dump.  This is the failed instruction:

```
(gdb) x/i $pc
=> 0x564efb3f4670 <_ZN14MinimizerIndexC2Ev+96>:	vmovdqu8 %ymm0,0x5c(%rdi)
```

From [the felixcloutier site](https://www.felixcloutier.com/x86/movdqu:vmovdqu8:vmovdqu16:vmovdqu32:vmovdqu64), `VMOVDQU8` is an AVX-512 instruction that is available through either the "AVX512VL" or the "AVX512BW" feature set.  That is why the program is crashing with "Illegal Instruction": The AMD EPYC "Rome" CPUs don't include support for any part of AVX512.

The illegal instruction was in `MinimizerIndex::MinimizerIndex`.  This class comes from [bifrost](https://github.com/pmelsted/bifrost), which the Kallisto folks are [vendoring](https://github.com/pachterlab/kallisto/tree/master/ext/bifrost).  The Biofrost README [has a section](https://github.com/pmelsted/bifrost#troubleshooting) that addresses this exact issue, saying "Bifrost is compiled in native mode such to target architecture instructions specific to the machine it is compiled on."

So, there is the problem: Whoever built kallisto for Bioconda built it on a machine with AVX-512.

In the [installation section](https://github.com/pmelsted/bifrost#installation) of the bifrost README, it describes two options you can use to control what sorts of CPU features are used.  But I don't know enough about cmake to know how to do that inside Kallisto itself.

**Comment by mjsteinbaugh** [comment]
This should be fixed in kallisto 0.50.1

**Comment by servalli** [comment]
The same problem still occurs with kallisto 0.50.1 build from Bioconda.

**Comment by MehdiFard** [comment]
I'm also getting the same error with Kallisto 0.50.1.

**Comment by mkiyer** [comment]
Confirm I am still having this error with Kallisto 0.50.1

**Comment by mkiyer** [comment]
I built and uploaded a working linux64 package mkiyer::kallisto=0.50.1 on my hardware

**Comment by perllb** [comment]
I am getting the same issue with kallisto==0.50.1, built from `https://github.com/pachterlab/kallisto/archive/v0.50.1.zip`

Strangely, it worked fine until I re-installed it from that same source yesterday. 

That is: it still works when running within a docker container that was built about 5 weeks ago (with kallisto installed from the source above). However, a new docker build from yesterday with the exact same recipe (except for also installing GNU parallel), throws this error.

**Comment by mschilli87** [comment]
I have hit this with kallisto 0.51.1. Could this maybe at least be re-opened to improve visibility? I would be happy to help fixing this.

**Comment by mschilli87** [comment]
Note that meanwhile I learned that the latest kallisto release distributes binaries that do not rely on modern CPU features: https://github.com/pachterlab/kallisto/issues/399#issuecomment-3830014463

I would like to get this into conda. I could provide a PR if there is interest.

**Comment by mschilli87** [comment]
OK: I am officially puzzled:
As per [kallisto's `.make_binaries`](https://github.com/pachterlab/kallisto/blob/master/.make_binaries.sh), the `*_optoff_k64` builds are using `cmake .. -DUSE_HDF5=ON -DUSE_BAM=ON -DBUILD_FUNCTESTING=ON -DENABLE_AVX2=OFF -DCOMPILATION_ARCH=OFF -DMAX_KMER_SIZE=64`.
`-DUSE_HDF5=ON -DUSE_BAM=ON -DBUILD_FUNCTESTING=ON -DMAX_KMER_SIZE=64` are used by bioconda unconditionally: https://github.com/bioconda/bioconda-recipes/blob/6bcc19287bb7f99a10c237c3024134780f20ae68/recipes/kallisto/build.sh#L58
That leaves `-DENABLE_AVX2=OFF -DCOMPILATION_ARCH=OFF`.
However, on `x86_64`, those are used by bioconda as well via `ARCH_OPTS`: https://github.com/bioconda/bioconda-recipes/blob/6bcc19287bb7f99a10c237c3024134780f20ae68/recipes/kallisto/build.sh#L27-L29 https://github.com/bioconda/bioconda-recipes/blob/6bcc19287bb7f99a10c237c3024134780f20ae68/recipes/kallisto/build.sh#L60
Thus, the `x86_64` build of bioconda should match upstream's `*_optoff_k64` already.
Regardless, the using the former crashes with SIGILL for me (`uname -m` *does* report `x86_64` on my system) whereas the latter works (using the exact same command and input). 🤔

**Comment by mschilli87** [comment]
I just confirmed that this is still the case with v. 0.52.0.

**Comment by mschilli87** [comment]
I am quite sure I finally figured this one out. 🥳 
See https://github.com/bioconda/bioconda-recipes/pull/69183 for details.

@servalli, @MehdiFard, @mkiyer: If any of you still have access to the hardware you reproduced this on, I'd be thankful if you could download and extract the zip file posted by the bot at that PR, add the extracted directory as a channel, and install `kallisto=0.52.0=hd638d68_1` from that local channel to confirm this works for you while just pulling in `kallisto=0.52.0` from the `bioconda` channel still fails.
