### ISSUE TITLE
broken SEPP recipe

### ISSUE THREAD

**Issue by luisas** [bioconda/bioconda-recipes#53780]
Hi all, 

the sepp recipe seems to have some issue - as run_upp.py when called with more than 100 sequences will not find the dependency hmmalign. I believe below 100 sequences hmmalign is not called at all, that is why for tiny tests the issue may not pop up. 

Here the issues I opened in their repo --> [issue](https://github.com/smirarab/sepp/issues/141).

This is the error I get 

`[13:19:43] config.py (line 371):     INFO: Seed number: 297834
[13:19:43] algorithm.py (line 150):     INFO: [Errno 2] No such file or directory: '/opt/conda/conda-bld/sepp_1724890798483/work/.sepp/bundled-v4.5.5/hmmbuild'
[13:19:43] algorithm.py (line 153):     INFO: UPP version 4.5.5 used with HMMER version (Unclear)
[13:19:43] algorithm.py (line 155):     INFO: Will user HMMER located at /opt/conda/conda-bld/sepp_1724890798483/work/.sepp/bundled-v4.5.5/hmmbuild
[13:19:43] algorithm.py (line 157):     INFO: All options: Namespace(pplacer=Namespace(path='/opt/conda/conda-bld/sepp_1724890798483/work/.sepp/bundled-v4.5.5/pplacer'), hmmalign=Namespace(path='/opt/conda/bin/hmmalign'), hmmsearch=Namespace(path='/opt/conda/conda-bld/sepp_1724890798483/work/.sepp/bundled-v4.5.5/hmmsearch', piped='False', elim='10000', filters='True'), hmmbuild=Namespace(path='/opt/conda/conda-bld/sepp_1724890798483/work/.sepp/bundled-v4.5.5/hmmbuild'), jsonmerger=Namespace(path='/opt/conda/conda-bld/sepp_1724890798483/work/.sepp/bundled-v4.5.5/seppJsonMerger.jar'), exhaustive=Namespace(strategy='centroid', minsubsetsize='2', placementminsubsetsizefacotr='4', placer='pplacer', weight_placement_by_alignment='True'), pasta=Namespace(path='run_pasta.py', user_options='--max-mem-mb=2000'), max_chunk_size=20000, distance=1, maxDiam=None, tempdir='/tmp/sepp', remtemp=False, output='output', outdir='/tmp', molecule='dna', ignore_overlap=False, cpu=8, checkpoint=<sepp.checkpointing.CheckPointManager object at 0x7f82c47d44f0>, checkpoint_interval=3600, seed=297834, alignment_size=10, full_length_range=None, median_full_length=None, backbone_threshold=0.25, backbone_size=None, decomp_strategy='hierarchical', sequence_file=None, config_file=<_io.TextIOWrapper name='test.config' mode='r' encoding='UTF-8'>, tree_file=None, alignment_file=None, backtranslation_sequence_file=None, long_branch_filter=None, placement_size=None, info_file=None, fragment_file=None)
`

Does someone have any idea how to fix it? 

I believe the authors of the tool may not be super responsive as the latest issues in their repo are unanswered :( 

I tried few things but I was unable to fix it - any help or hint is appreciated :)

**Comment by aliciaaevans** [comment]
fixed by https://github.com/bioconda/bioconda-recipes/pull/54193

**Comment by ebete** [comment]
Unfortunately, this was not completely fixed. Only the `run_sepp.py` script. `run_upp.py` still fails with `hmmbuild` not found.
