### ISSUE TITLE
OSX builds fail

### ISSUE THREAD

**Issue by mbargull** [bioconda/bioconda-recipes#6950]
@bioconda/core
OSX builds currently fail. Travis image changed from
`travis-ci-osx10.11-xcode7.3-1480691248 (via amqp)`
to
`travis-ci-macos10.12-xcode8.3-1507738863 (via amqp)`
and now pip is not found:
```
+pip install pyyaml
scripts/travis-setup.sh: line 25: pip: command not found
```

**Comment by mbargull** [comment]
Resolved by #6952.

**Comment by johanneskoester** [comment]
Excellent work, @mbargull!

**Comment by matthdsm** [comment]
Hi, 

Thanks for the quick fix. However, it didn't work for #6948, pip is still missing.
Cheers
M
