### ISSUE TITLE
fastqc needs fonts, no fonts in container

### ISSUE THREAD

**Issue by charlesreid1** [bioconda/bioconda-recipes#8586]
Hi,

I am running a workflow that involves a step with fastqc. I'm running into a problem in the last step of fastqc, when it has completed the analysis and is attempting to generate a report. The Java engine is crashing because it cannot find font files it needs.

From inside container:

```
$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (Zulu 8.20.0.5-linux64) (build 1.8.0_121-b15)
OpenJDK 64-Bit Server VM (Zulu 8.20.0.5-linux64) (build 25.121-b15, mixed mode)
```

Here's the command I was running:

```
docker run \
    -u $(id -u):$(id -g) \
    -v /home/ubuntu/dahak-taco/data:/data/ \
    -it \
    quay.io/biocontainers/fastqc:0.11.7--pl5.22.0_0 \
    fastqc \
    -t 1 \
    /data/SRR606249_1_reads.fq.gz \
    -o /data/
```

And here's the output that was printed:

```
Approx 50% complete for SRR606249_1_reads.fq.gz
Approx 55% complete for SRR606249_1_reads.fq.gz
Approx 60% complete for SRR606249_1_reads.fq.gz
Approx 65% complete for SRR606249_1_reads.fq.gz
Approx 70% complete for SRR606249_1_reads.fq.gz
Approx 75% complete for SRR606249_1_reads.fq.gz
Approx 80% complete for SRR606249_1_reads.fq.gz
Approx 85% complete for SRR606249_1_reads.fq.gz
Approx 90% complete for SRR606249_1_reads.fq.gz
Approx 95% complete for SRR606249_1_reads.fq.gz
Analysis complete for SRR606249_1_reads.fq.gz
Exception in thread "Thread-1" java.lang.Error: Probable fatal error:No fonts found.
        at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1236)
        at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
        at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
        at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
        at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
        at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
        at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
        at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
        at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
        at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
        ...
```

It seems the recipe needs to be updated so it installs the Java package that is missing. I don't know what package that is, but someone more knowledgeable about Java packaging than I may find it in the [fastqc](https://github.com/s-andrews/FastQC) repository.

**Comment by epruesse** [comment]
sounds like #5026 is still a problem

**Comment by charlesreid1** [comment]
Thank you for the link! It sounds like this has been an ongoing issue, and the TL;DR is that `openjdk` in the container needs to come from `conda-forge`, but is actually coming from `default`. 

It seems from the Dockerfile that @ewels included in his comment that it "should" be a straightforward change from `conda install openjdk` to `conda install conda-forge::openjdk` in the recipe. I think that would occur on [this line](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/fastqc/meta.yaml#L22). Like this?

```
requirements:
  run:
    - "conda-forge::openjdk"
    - perl
```


(Side note: I'm a bit confused by the [fastqc recipe](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/fastqc), it looks like 0.11.7 was rolled into the files for 0.11.6, rather than a separate/new version being made...)

**Comment by epruesse** [comment]
Yes, that should fix it. At least, it works for me in my Snakemake stuff:

https://github.com/epruesse/ymp/blob/adef97777ba4b76edf0766b5fdcf99147303abef/src/ymp/rules/fastqc.rules#L1-L5

**Comment by charlesreid1** [comment]
Oh wonderful, I had completely forgotten that you can modify Snakemake's `env` locally.

**Comment by MaxUlysse** [comment]
Just tried the fastqc 0.11.7 bioconda, and I still have the missing font problem.
I think that the recipe is still not fixed.

**Comment by MaxUlysse** [comment]
Nevermind, I was asking the channels in the wrong order....
Sorry

**Comment by milimz** [comment]
this : 
conda install conda-forge::openjdk 
actually fix my problem!
