### ISSUE TITLE
circleci build fails locally when testing recipes.

### ISSUE THREAD

**Issue by rhpvorderman** [bioconda/bioconda-recipes#9538]
New version of biopet-seqstat succeeds when build with circleci: https://github.com/bioconda/bioconda-recipes/pull/9487

Unfortunately it fails locally. I have circleci installed as a snap. Issuing the command `circleci build` in the root of bioconda recipes gives the following error:
```
recipes/biopet-seqstat
 recipes/biopet-seqstat/0.1
 recipes/biopet-seqstat/1.0
11:59:20 BIOCONDA DEBUG lint recipes/biopet-seqstat
11:59:20 BIOCONDA DEBUG lint recipes/biopet-seqstat/0.1
11:59:20 BIOCONDA DEBUG lint recipes/biopet-seqstat/1.0
====>> Testing
  #!/bin/bash -eo pipefail
bioconda-utils build recipes config.yml \
--git-range master HEAD \
--prelint

usage: bioconda-utils [-h]
                      {build,dag,dependent,lint,duplicates,bioconductor-skeleton,pypi-check,clean-cran-skeleton}
                      ...
bioconda-utils: error: unrecognized arguments: --prelint
Error: Exited with code 2
Step failed
Task failed
```
This means the local test does not reflect the result of the remote test, which is undesirable.

**Comment by bbsunchen** [comment]
My local test stuck here, even I did not make any changes to the master repo.

**Comment by brantfaircloth** [comment]
I'm seeing this too.  It appears it may have been this commit to bioconda-utils in the `build-lint-only-exclude` branch: https://github.com/bioconda/bioconda-utils/commit/4db60acd4da331f35a2aecdc6a580a9f3c66d2df

**Comment by thw17** [comment]
I'm seeing this as well

**Comment by asmariyaz23** [comment]
I get this error too.

**Comment by bgruening** [comment]
Are you on latest master of bioconda-recipes? How do you run the tests?

**Comment by brantfaircloth** [comment]
I’ll pull from master again on monday... pretty sure I did that friday before posting, but I also now see commit from ~19 June that should fix...

**Comment by asmariyaz23** [comment]
I happened to clone this yesterday (June 22) and see this issue.

**Comment by thw17** [comment]
I pulled yesterday (June 22) as well. All steps that I took, etc. followed the contributing section on the main page exactly. I had no issues as of June 15.

**Comment by mbargull** [comment]
We're currently using the Docker tag `bioconda/bioconda-utils-build-env:cb3-migration` instead of `bioconda/bioconda-utils-build-env:latest` for the `conda-build 3` migration but didn't update the local `build` job accordingly.
Should be fixed now. If not, please reopen the issue.

**Comment by brantfaircloth** [comment]
@mbargull  I just hit this same issue again (local build on 27 July 1645 GMT).  I made sure the bioconda-recipes repo is up to date and ran `circleci update` this morning.


```
====>> Linting
  #!/bin/bash -eo pipefail
bioconda-utils lint recipes config.yml \
--loglevel debug --full-report \
--git-range master HEAD

16:42:11 BIOCONDA INFO Recipes newly unblacklisted:

16:42:11 BIOCONDA INFO Recipes to consider according to git:
recipes/phyluce
16:42:11 BIOCONDA DEBUG get_recipes(recipes, package='['*']'): *
16:42:11 BIOCONDA DEBUG recipes/phyluce
16:42:11 BIOCONDA INFO Recipes to lint:
recipes/phyluce
16:42:11 BIOCONDA DEBUG lint recipes/phyluce
====>> Testing
  #!/bin/bash -eo pipefail
bioconda-utils build recipes config.yml \
--git-range master HEAD \
--prelint

usage: bioconda-utils [-h]
                      {build,dag,dependent,lint,duplicates,bioconductor-skeleton,pypi-check,clean-cran-skeleton}
                      ...
bioconda-utils: error: unrecognized arguments: --prelint
Error: Exited with code 2
Step failed
Task failed
```

**Comment by nsoranzo** [comment]
> @mbargull I just hit this same issue again (local build on 27 July 1645 GMT). I made sure the bioconda-recipes repo is up to date and ran circleci update this morning.

Same here.

**Comment by micknudsen** [comment]
I get the same error (circleci 0.1.2001+d9f59f7). May very well be related to this error a few steps before:

```
====>> Setup bioconda-utils
  #!/bin/bash -eo pipefail
.circleci/setup.sh
From https://github.com/bioconda/bioconda-recipes
 * [new branch]          master     -> __upstream__WlLjdT9bAb/master
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Does anybody else have problems with access rights?

**Comment by asmariyaz23** [comment]
I get the same error again, it got fixed earlier. circleci updated and using the most recent bioconda clone. @mbargull any pointers would be helpful. thank you :)

**Comment by rhpvorderman** [comment]
I get another error when testing:
```
[info]   #!/bin/bash -eo pipefail
[info] .circleci/setup.sh
[info] /opt/docker/bin/entrypoint_source: line 11: conda: command not found
[info] /opt/docker/bin/entrypoint_source: line 11: conda: command not found
[info] /opt/docker/bin/entrypoint_source: line 11: conda: command not found
```

**Comment by tstrnity** [comment]
Had this same problem today: 2018/09/11
Any help as to how to fix or get around this would be greatly appreciated.

To make sure I was up to date, from my user (tstrnity) on the github website I made a new fork from the github repository. Cloned to my test platform, made a new branch for the recipe I am modifying. Put modifications in place. Then ran:
$ circleci build
Docker image digest: sha256:525c91e01875050fbf65cdb4bc83a45744c54f9027fa05f76f88713f3d37f4e3
====>> Spin up Environment
Build-agent version 0.0.7725-9681bc36 (2018-08-09T15:10:50+0000)
Starting container bioconda/bioconda-utils-build-env
  using image bioconda/bioconda-utils-build-env@sha256:df0afa701df04e07a294e4cfce05641fddacf934a46492742a5986f367bc554e

Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1536686715
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=ctat-mutations
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=git@github.com:tstrnity/bioconda-recipes.git
  CIRCLE_SHA1=160d881260a52222817b000b3e06dca8228876b4
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1536686715
  CIRCLE_WORKING_DIRECTORY=~/project

====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project
====>> Setup ssh
  #!/bin/bash -eo pipefail
mkdir -p ~/.ssh
ssh-keyscan -H github.com >> ~/.ssh/known_hosts

# github.com SSH-2.0-libssh_0.7.0
====>> Setup base system
  #!/bin/bash -eo pipefail
cat >> $BASH_ENV <<EOF
if [[ \$- == *u* ]] ; then
    set +u ; . /tmp/repo/docker-entrypoint-source ; set -u
else
    . /tmp/repo/docker-entrypoint-source
fi
EOF

====>> Download common definitions
  #!/bin/bash -eo pipefail
curl -s https://raw.githubusercontent.com/bioconda/bioconda-common/master/common.sh > .circleci/common.sh

====>> Setup bioconda-utils
  #!/bin/bash -eo pipefail
.circleci/setup.sh
From https://github.com/bioconda/bioconda-recipes
 * [new branch]          master     -> __upstream__kT7xHBgsSQ/master
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
====>> Linting
  #!/bin/bash -eo pipefail
bioconda-utils lint recipes config.yml \
--loglevel debug --full-report \
--git-range master HEAD

17:25:55 BIOCONDA INFO Recipes newly unblacklisted:

17:25:55 BIOCONDA INFO Recipes to consider according to git: 
recipes/ctat-mutations
 recipes/ctat-mutations
17:25:55 BIOCONDA DEBUG get_recipes(recipes, package='['*']'): *
17:25:56 BIOCONDA DEBUG recipes/ctat-mutations
17:25:56 BIOCONDA INFO Recipes to lint:
recipes/ctat-mutations
17:25:56 BIOCONDA DEBUG lint recipes/ctat-mutations
====>> Testing
  #!/bin/bash -eo pipefail
bioconda-utils build recipes config.yml \
--git-range master HEAD \
--prelint

usage: bioconda-utils [-h]
                      {build,dag,dependent,lint,duplicates,bioconductor-skeleton,pypi-check,clean-cran-skeleton}
                      ...
bioconda-utils: error: unrecognized arguments: --prelint
Error: Exited with code 2
Step failed
Error: runner failed
Task failed

**Comment by tstrnity** [comment]
Additional info:
Apparently I needed to update the bioconda-utils-build_env, but doing that results in a different error even sooner in the process, the same error that @rhpvorderman reports:
I did 
$ docker pull bioconda/bioconda-utils-build-env
then:
$ circleci build
Docker image digest: sha256:525c91e01875050fbf65cdb4bc83a45744c54f9027fa05f76f88713f3d37f4e3
====>> Spin up Environment
Build-agent version 0.0.7725-9681bc36 (2018-08-09T15:10:50+0000)
Starting container bioconda/bioconda-utils-build-env
  using image bioconda/bioconda-utils-build-env@sha256:ea59154ebeb07cbe1bb555148a67d4559bb11c6867592b7e3e5cd7e0a46cf298

Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1536758011
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=ctat-mutations
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=git@github.com:tstrnity/bioconda-recipes.git
  CIRCLE_SHA1=160d881260a52222817b000b3e06dca8228876b4
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1536758011
  CIRCLE_WORKING_DIRECTORY=~/project

====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project
====>> Setup ssh
  #!/bin/bash -eo pipefail
mkdir -p ~/.ssh
ssh-keyscan -H github.com >> ~/.ssh/known_hosts

# github.com SSH-2.0-libssh_0.7.0
====>> Setup base system
  #!/bin/bash -eo pipefail
cat >> $BASH_ENV <<EOF
if [[ \$- == *u* ]] ; then
    set +u ; . /tmp/repo/docker-entrypoint-source ; set -u
else
    . /tmp/repo/docker-entrypoint-source
fi
EOF

====>> Download common definitions
  #!/bin/bash -eo pipefail
curl -s https://raw.githubusercontent.com/bioconda/bioconda-common/master/common.sh > .circleci/common.sh

/opt/docker/bin/entrypoint_source: line 11: conda: command not found
====>> Setup bioconda-utils
  #!/bin/bash -eo pipefail
.circleci/setup.sh
/opt/docker/bin/entrypoint_source: line 11: conda: command not found
/opt/docker/bin/entrypoint_source: line 11: conda: command not found
/opt/docker/bin/entrypoint_source: line 11: conda: command not found
Error: Exited with code 127
Step failed
Error: runner failed
Task failed

**Comment by johanneskoester** [comment]
Ok, first, the --prelint issue should be fixed now in PR #10920.

**Comment by johanneskoester** [comment]
Regarding the conda not found problem, I am looking into that now.

**Comment by johanneskoester** [comment]
Ok, problem solved. One fix is in PR #10920, the other in https://github.com/bioconda/bioconda-utils/pull/333.

**Comment by johanneskoester** [comment]
Once these PRs are merged and a new bioconda-utils version is released, it should work again. Sorry for the inconvenience.

**Comment by johanneskoester** [comment]
Should be fixed and deployed now.

**Comment by micknudsen** [comment]
It still fails for me. I have pulled the latest upstream master and merged it into my branch. The following happens:

```
====>> Setup bioconda-utils
  #!/bin/bash -eo pipefail
.circleci/setup.sh
/tmp/.bash_env-localbuild-1536919183: line 1: /opt/conda/etc/profile.d/conda.sh: No such file or directory
/tmp/.bash_env-localbuild-1536919183: line 2: conda: command not found
/tmp/.bash_env-localbuild-1536919183: line 1: /opt/conda/etc/profile.d/conda.sh: No such file or directory
/tmp/.bash_env-localbuild-1536919183: line 2: conda: command not found
/tmp/.bash_env-localbuild-1536919183: line 1: /opt/conda/etc/profile.d/conda.sh: No such file or directory
Error: Exited with code 1
Step failed
Error: runner failed
Task failed
```

**Comment by bgruening** [comment]
@micknudsen please update your build-infrastructure ...

**Comment by micknudsen** [comment]
@bgruening I have run both `circleci update build-agent`and `circleci update install`, but I still get the same error.

**Comment by mbargull** [comment]
Did you run
```sh
docker pull bioconda/bioconda-utils-build-env
```
? (ref: http://bioconda.github.io/contribute-a-recipe.html#circle-ci-client-method)

**Comment by micknudsen** [comment]
@mbargull Thanks! I completely missed what was the cause of the problem. Thought it had to do with circleci itself. Everything works perfectly now!
